### ISSUE TITLE
A question about preprocessing and evaluation

### ISSUE THREAD

**Issue by speedcell4** [yahshibu/nested-ner-2019#2]
Hello,

I ran your `parse_ace2005.py` to preprocess ACE2005 dataset, and I noticed there are some duplicated entities in the obtained files. For instance, in the train split, I found a sentence like below,

```
We 'll have a couple of experts come out , so I 'll withhold my comments until then .
0,1 ORG|3,7 PER|3,7 PER|11,12 PER|14,15 PER
```
where the `3,7 PER` appears twice. Is this correct?

And then I checked your evaluation function,

https://github.com/yahshibu/nested-ner-tacl2020/blob/7698f20c67c0d54f5d479b3f3aec0aeadbdf8f12/util/evaluate.py#L5-L20

seems you do not remove the duplicated entities, so does this have any influence on the final evaluation results?

**Comment by speedcell4** [comment]
And I also noticed your dataset statistics are different from previous work.
For example, [[Lu+ 2015]](https://www.aclweb.org/anthology/D15-1102.pdf) reports the train/dev/test splits of ACE2005 contain 7336/958/1047 sentences, while according to your [Table 1](https://arxiv.org/pdf/1909.02250v3.pdf), these numbers become 7285/968/1058.
Could you please explain the reason?

**Comment by yahshibu** [comment]
Hello, thank you for having an interest in our work.

The result of the sentence split relies on a tokenizer because ACE-2005 corpus doesn't have information about sentence split. We use Stanford CoreNLP, but we also saw that different numbers were obtained when we used spaCy. In addition to using Stanford CoreNLP, we applied heuristic preprocessing referring to [Muis and Lu (2017)](https://www.aclweb.org/anthology/D17-1276/)'s implementation ([here](https://github.com/justhalf/java-nlp-toolkit/blob/master/src/main/java/justhalf/nlp/reader/acereader/ACEReader.java)). The numbers are derived from this combination.

In terms of duplicated entities, it is correct. And, it can have an influence on Recall and F1 scores. This follows the way of the evaluation of [Wang and Lu (2018)](https://www.aclweb.org/anthology/D18-1019/). They counted duplicated entities.

https://github.com/berlino/overlapping-ner-em18/blob/c2db301cfd88c4ab51694d816fce6c2dcb75c5b9/reader/reader.py#L67

https://github.com/berlino/overlapping-ner-em18/blob/master/util/evaluate.py

I've seen the number of duplicated entities in the ACE-2005 test set is 11. And, I've calculated scores in the case where we remove the duplicated entities on ACE-2005.

- Precision: 78.27 ± 0.81
- Recall: 75.44 ± 0.36
- F1: 76.83 ± 0.35

The standard deviations of Recall and F1 have slightly changed, but the changes are tiny. Most duplicated entities are correctly detected, but some duplicated entities are missed. This is why the changes are tiny.

**Comment by speedcell4** [comment]
Thank you for your quick and detailed response. That is really helpful!

**Comment by yahshibu** [comment]
You're welcome! Please feel free to ask if you come up with a new question.
